### ISSUE TITLE
Spigot 1.10 loading issue

### ISSUE THREAD

**Issue by frizzbee30** [cybertiger/Bukkit-CreativeItemControl#4]
Hi, incompatible with 1.10, hope you can update as it really is a fantastic plugin!

**Comment by WebShark025** [comment]
+1, Not works on 1.10.

**Comment by NachtRaben** [comment]
+1, Looking to use this on a large network.

**Comment by WebShark025** [comment]
I even tried to compile wiith Spigot 1.10 myself, but It couldnt register some event i think. Thats why i stopped working on it.

**Comment by cybertiger** [comment]
Fixed, will post to spigotmc.org shortly.

**Comment by frizzbee30** [comment]
fantastic  :)

**Comment by cybertiger** [comment]
Found a bug, will hopefully get it fixed and deployed tomorrow night.

**Comment by frizzbee30** [comment]
hi, just wondering if the update will be released this weekend?  Thanks

**Comment by RoboMWM** [comment]
> Found a bug, will hopefully get it fixed and deployed tomorrow night.

Any details on this bug @cybertiger? Otherwise I'm just going to compile from here and expect it to be okay..

**Comment by frizzbee30** [comment]
Hi, any update on this,as it really is one of our 'cornerstone' plugins! :)

**Comment by RoboMWM** [comment]
Yes, #7

**Comment by frizzbee30** [comment]
kindly updated by another dev
